name: 'oc new-app'
description: 'Deploy and Expose an app on Openshift'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  image:
    description: 'The name (reference) of the image to create deployment'
    required: true
  port:
    description: 'The port to use for the application'
    required: false
  app_name:
    description: 'Name to use for generated application artifacts'
    required: true
outputs:
  route:
    description: 'Service route of the deployed application'
runs:
  using: 'node12'
  main: 'dist/index.js'
