name: 'oc-new-app'
description: 'Deploy and expose an application on OpenShift'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  app_name:
    description: "Name to use for generated application artifacts"
    required: true
  create_pull_secret_from:
    description: |
      "Registry credentials file to use to create a pull secret.
      Set this to "docker" or "podman" depending on which tool you used to log in"
    required: false
  image:
    description: "The name (reference) of the image to create deployment"
    required: true
  image_pull_secret_name:
    description: |
      "In the case of private images, provide the image pull secret if you have already created that.
      Otherwise, provide inputs create_pull_secret_from or registry_hostname, registry_username and registry_password"
    required: false
  namespace:
    description: "The OpenShift project/Kubernetes namespace to deploy to. Defaults to current context's."
    required: false
  port:
    description: "The port to use for the application"
    required: false
  registry_hostname:
    description: "The Hostname/domain of the container image registry such as quay.io, docker.io. to create pull secret"
    required: false
  registry_username:
    description: "Registry username to use for the pull secret"
    required: false
  registry_password:
    description: "Password, encrypted password, or access token of the provided registry to use for the pull secret"
    required: false

outputs:
  route:
    description: "Service route of the deployed application"
  selector:
    description: "Selector to filter out the deployment"
runs:
  using: 'node12'
  main: 'dist/index.js'
