name: 'oc-new-app'
description: 'Deploy and expose an application on OpenShift'
author: 'Red Hat'
branding:
  icon: circle
  color: red
inputs:
  app_name:
    description: "Name to use for generated application artifacts"
    required: true
  image:
    description: "The name (reference) of the image to create deployment"
    required: true
  namespace:
    description: "The OpenShift project/Kubernetes namespace to deploy to. Defaults to current context's."
    required: false
  port:
    description: "The port to use for the application"
    required: false
outputs:
  route:
    description: "Service route of the deployed application"
  selector:
    description: "Selector to filter out the deployment"
runs:
  using: 'node12'
  main: 'dist/index.js'
